# -*- coding: utf-8 -*-
"""dealsize_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdO173CSyPFZyBeFCwF1HUtF5KteGZae
"""

import json
import sys
import warnings
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, OneHotEncoder, StandardScaler

warnings.filterwarnings("ignore", category=UserWarning)

from pathlib import Path

DATA_PATH = "/content/drive/MyDrive/PythonTesting/Auto Sales data.csv"   # change to your GitHub raw URL or local path
OUTPUT_DIR = Path("artifacts")

RANDOM_STATE = 42
TEST_SIZE = 0.2

RAW_NUM_FEATURES = [
    "QUANTITYORDERED",
    "PRICEEACH",
    "ORDERLINENUMBER",
    "DAYS_SINCE_LASTORDER",
    "MSRP",
]
DATE_COL = "ORDERDATE"
ENGINEERED_NUM_FEATURES = RAW_NUM_FEATURES + ["ORDER_MONTH", "ORDER_YEAR"]
CAT_FEATURES = ["PRODUCTLINE", "COUNTRY"]

# Business-meaningful ordinal target mapping (NOT alphabetical LabelEncoder).
DEALSIZE_ORDER = ["Small", "Medium", "Large"]
LABEL_MAP = {label: idx for idx, label in enumerate(DEALSIZE_ORDER)}
INVERSE_LABEL_MAP = {idx: label for label, idx in LABEL_MAP.items()}
LARGE_CLASS_INDEX = LABEL_MAP["Large"]

import pandas as pd

def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    return df

def add_date_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df[DATE_COL] = pd.to_datetime(df[DATE_COL], format="%d/%m/%Y")
    df["ORDER_MONTH"] = df[DATE_COL].dt.month
    df["ORDER_YEAR"] = df[DATE_COL].dt.year
    df = df.drop(columns=[DATE_COL])
    return df


def build_date_transformer() -> FunctionTransformer:
    return FunctionTransformer(add_date_features, validate=False)

from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

def build_preprocessor() -> ColumnTransformer:
    numeric_pipeline = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')), ("scaler", StandardScaler())])
    categorical_pipeline = Pipeline(
        steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown="ignore"))
        ]
    )
    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_pipeline, ENGINEERED_NUM_FEATURES),
            ("cat", categorical_pipeline, CAT_FEATURES),
        ]
    )
    return preprocessor

def tune_model(pipeline: Pipeline, X_train, y_train) -> GridSearchCV:
    param_grid = {
        "model__C": [0.01, 0.1, 1, 10, 100],
        "model__class_weight": [
            "balanced",
            {0: 1, 1: 1, 2: 1.5},
            {0: 1, 1: 1, 2: 2},
            {0: 1, 1: 1, 2: 1},
        ],
        "model__solver": ["lbfgs"],
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

    grid_search = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        cv=cv,
        scoring="f1_macro",
        n_jobs=-1,
        refit=True,
    )
    grid_search.fit(X_train, y_train)
    return grid_search

def predict_with_large_threshold(model, X, large_threshold: float = 0.5) -> np.ndarray:
    proba = model.predict_proba(X)
    preds = np.argmax(proba, axis=1)

    if large_threshold != 0.5:
        large_col = model.classes_.tolist().index(LARGE_CLASS_INDEX)
        for i in range(len(preds)):
            if proba[i, large_col] >= large_threshold:
                preds[i] = LARGE_CLASS_INDEX
            elif preds[i] == LARGE_CLASS_INDEX:
                # Large no longer clears the bar -> fall back to the next
                # best non-Large class for this row.
                remaining = [c for c in range(proba.shape[1]) if c != large_col]
                remaining_proba = proba[i, remaining]
                preds[i] = remaining[int(np.argmax(remaining_proba))]
    return preds


def scan_thresholds(model, X_test, y_test, thresholds=(0.3, 0.4, 0.5, 0.6, 0.7)) -> pd.DataFrame:
    rows = []
    for t in thresholds:
        preds = predict_with_large_threshold(model, X_test, large_threshold=t)
        rows.append(
            {
                "threshold": t,
                "large_precision": precision_score(
                    y_test, preds, labels=[LARGE_CLASS_INDEX], average="micro"
                ),
                "large_recall": recall_score(
                    y_test, preds, labels=[LARGE_CLASS_INDEX], average="micro"
                ),
                "overall_accuracy": accuracy_score(y_test, preds),
                "overall_f1_macro": f1_score(y_test, preds, average="macro"),
            }
        )
    return pd.DataFrame(rows)

def evaluate(model, X_train, y_train, X_test, y_test) -> dict:
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    test_proba = model.predict_proba(X_test)

    report = {
        "train_accuracy": accuracy_score(y_train, train_pred),
        "test_accuracy": accuracy_score(y_test, test_pred),
        "test_precision_weighted": precision_score(y_test, test_pred, average="weighted"),
        "test_recall_weighted": recall_score(y_test, test_pred, average="weighted"),
        "test_f1_weighted": f1_score(y_test, test_pred, average="weighted"),
        "roc_auc_ovr_macro": roc_auc_score(
            y_test, test_proba, multi_class="ovr", average="macro"
        ),
        "classification_report": classification_report(
            y_test, test_pred, target_names=DEALSIZE_ORDER, output_dict=True
        ),
        "confusion_matrix": confusion_matrix(y_test, test_pred).tolist(),
    }
    return report


def print_report(report: dict, cv_scores: np.ndarray) -> None:
    print("=" * 60)
    print("MODEL EVALUATION REPORT")
    print("=" * 60)
    print(f"Train Accuracy       : {report['train_accuracy']:.2%}")
    print(f"Test Accuracy        : {report['test_accuracy']:.2%}")
    print(f"Precision (weighted) : {report['test_precision_weighted']:.2%}")
    print(f"Recall (weighted)    : {report['test_recall_weighted']:.2%}")
    print(f"F1 (weighted)        : {report['test_f1_weighted']:.2%}")
    print(f"ROC-AUC (macro, OvR) : {report['roc_auc_ovr_macro']:.4f}")
    print(f"5-Fold CV Accuracy   : {cv_scores.mean():.2%} (+/- {cv_scores.std():.2%})")
    print("\n--- Per-class breakdown ---")
    for cls in DEALSIZE_ORDER:
        stats = report["classification_report"][cls]
        print(
            f"{cls:8s} precision={stats['precision']:.2f}  "
            f"recall={stats['recall']:.2f}  f1={stats['f1-score']:.2f}  "
            f"support={int(stats['support'])}"
        )
    print("\n--- Confusion Matrix (rows=actual, cols=predicted) ---")
    print(f"Order: {DEALSIZE_ORDER}")
    for row in report["confusion_matrix"]:
        print(row)
    print("=" * 60)

def save_artifacts(model, report: dict, chosen_threshold: float) -> None:
    OUTPUT_DIR.mkdir(exist_ok=True)

    joblib.dump(model, OUTPUT_DIR / "dealsize_pipeline.pkl")

    with open(OUTPUT_DIR / "label_map.json", "w") as f:
        json.dump(
            {"label_to_index": LABEL_MAP, "index_to_label": INVERSE_LABEL_MAP},
            f,
            indent=2,
        )

    with open(OUTPUT_DIR / "inference_config.json", "w") as f:
        json.dump(
            {
                "large_class_index": LARGE_CLASS_INDEX,
                "large_threshold": chosen_threshold,
                "required_input_columns": RAW_NUM_FEATURES + [DATE_COL] + CAT_FEATURES,
                "date_format": "%d/%m/%Y",
            },
            f,
            indent=2,
        )

    with open(OUTPUT_DIR / "evaluation_report.json", "w") as f:
        json.dump(report, f, indent=2)

    print(f"\nArtifacts saved to: {OUTPUT_DIR.resolve()}")
    print("  - dealsize_pipeline.pkl   (full pipeline: date features + scaling + encoding + model)")
    print("  - label_map.json          (Small=0, Medium=1, Large=2 - ordinal, business-meaningful)")
    print("  - inference_config.json   (required columns, chosen threshold, date format)")
    print("  - evaluation_report.json  (full metrics for record-keeping)")

def find_artifact(filename: str) -> Path:
    """Locate a saved artifact regardless of whether it sits in artifacts/ or beside the code.

    Training writes to artifacts/, but some deployments flatten everything into the
    repository root, so both layouts have to be searched.
    """
    module_dir = Path(__file__).resolve().parent
    candidates = [
        module_dir / OUTPUT_DIR.name / filename,
        module_dir / filename,
        Path.cwd() / OUTPUT_DIR.name / filename,
        Path.cwd() / filename,
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate

    tried = "\n  ".join(str(c) for c in candidates)
    raise FileNotFoundError(f"Could not find artifact {filename!r}. Tried:\n  {tried}")


def load_pipeline() -> tuple[Pipeline, dict]:
    """Load the trained pipeline and its inference config.

    Use this instead of calling joblib.load directly. The pipeline was trained in a
    notebook, where add_date_features lived in the __main__ namespace, so the pickled
    FunctionTransformer stores its func as a *reference* to __main__.add_date_features
    rather than a copy. Unpickling therefore fails with an AttributeError unless that
    name is resolvable on whichever module is registered as __main__ at load time.
    Binding it here keeps the workaround in one place.
    """
    main_module = sys.modules.get("__main__")
    if main_module is not None and not hasattr(main_module, "add_date_features"):
        main_module.add_date_features = add_date_features

    model = joblib.load(find_artifact("dealsize_pipeline.pkl"))

    with open(find_artifact("inference_config.json")) as f:
        config = json.load(f)

    return model, config

def predict_new_data(model, raw_df: pd.DataFrame, large_threshold: float = 0.5) -> pd.DataFrame:
    required_cols = RAW_NUM_FEATURES + [DATE_COL] + CAT_FEATURES
    missing = set(required_cols) - set(raw_df.columns)
    if missing:
        raise ValueError(f"Missing required columns for prediction: {missing}")

    X_new = raw_df[required_cols]
    preds = predict_with_large_threshold(model, X_new, large_threshold=large_threshold)
    proba = model.predict_proba(X_new)

    result = raw_df.copy()
    result["PREDICTED_DEALSIZE"] = [INVERSE_LABEL_MAP[p] for p in preds]
    result["CONFIDENCE"] = proba.max(axis=1)
    return result

def build_pipeline() -> Pipeline:
    date_transformer = build_date_transformer()
    preprocessor = build_preprocessor()
    model = LogisticRegression(random_state=RANDOM_STATE)
    pipeline = Pipeline(
        steps=[
            ("date_features", date_transformer),
            ("preprocessor", preprocessor),
            ("model", model),
        ]
    )
    return pipeline

def main():
    # 1. Load
    df = load_data(DATA_PATH)

    # 2. Build X / y. SALES intentionally excluded (target leakage).
    #    ORDERDATE kept RAW here - date engineering happens inside the pipeline.
    X = df[RAW_NUM_FEATURES + [DATE_COL] + CAT_FEATURES]
    y = df["DEALSIZE"].map(LABEL_MAP).values

    # 3. Split (stratified, since Large is a minority class).
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )

    # 4. Build pipeline and tune hyperparameters.
    pipeline = build_pipeline()
    grid_search = tune_model(pipeline, X_train, y_train)
    best_model = grid_search.best_estimator_

    print("Best hyperparameters found:")
    print(grid_search.best_params_)
    print(f"Best CV f1_macro during search: {grid_search.best_score_:.4f}\n")

    # 5. Cross-validate the FINAL chosen model on the full training set for
    #    a stability check independent of the grid search's internal CV.
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    cv_scores = cross_val_score(best_model, X_train, y_train, cv=cv, scoring="accuracy")

    # 6. Evaluate at default threshold (0.5).
    report = evaluate(best_model, X_train, y_train, X_test, y_test)
    print_report(report, cv_scores)

    # 7. Scan Large-class thresholds to show the precision/recall tradeoff,
    #    then pick a threshold (default 0.5 unless business says otherwise).
    threshold_scan = scan_thresholds(best_model, X_test, y_test)
    print("\n--- Large-class threshold scan (precision/recall tradeoff) ---")
    print(threshold_scan.to_string(index=False))
    chosen_threshold = 0.5  # adjust after reviewing the scan above with stakeholders

    # 8. Save everything needed for deployment.
    save_artifacts(best_model, report, chosen_threshold)

    return best_model, report


if __name__ == "__main__":
    trained_model, eval_report = main()
